### ISSUE TITLE
multi_select select_type: bootstrap_select would be awesome

### ISSUE THREAD

**Issue by phaidros7** [vedmack/yadcf#121]
besides chosen and select2 it would be fantastic to get bootstrap-select as select_type into yadcf!

http://silviomoreto.github.io/bootstrap-select/

**Comment by makronetz-patricia** [comment]
"adding class selectpicker to a multi_select"
----> could you post an example please? I could not manage to add a custom class to the select.

Thank you very much.

**Comment by vedmack** [comment]
@makronetz-patricia , if you whish to add a custom class to a select element you should keep an eye on this issue https://github.com/vedmack/yadcf/issues/163 because it will be implemented before the current one

**Comment by vedmack** [comment]
@phaidros7 , since you said that `adding class selectpicker to a multi_select is fine enough` I will close this issue because of the following recently added feature `style_class` - allows adding additional class/classes to filter - available for the following filters: select / multi_select / text / custom_func / multi_select_custom_func https://github.com/vedmack/yadcf/issues/163
