### ISSUE TITLE
some questions about initMultipleColumns

### ISSUE THREAD

**Issue by zxishere** [vedmack/yadcf#152]
the demo page: http://yadcf-showcase.appspot.com/dom_multi_columns_tables_1.10.html
when i search  "**Project 1 - 1**" in the left top search field 'First table columns 1 and 2!', **there's "No matching records found**, is something wrong?

I want use the initMultipleColumns function in my custom  search field ,so i can  replace Datatables default search field. Some reason like #133 . if i display datatime in my datatable columns, i don't want to search the value datatime column in the Datatables right top default search field, but i need filter it in the yadcf with datapicker.If i set searchable false , i can't filter it with yadcf datapicker.

I updated the 0.8.7.beta.10 version in my project, ,i saw  sql is "select columns 1 like "%value%" **AND** columns 2  like "%value%" .
id there  way to search with **OR** ?

**Comment by vedmack** [comment]
Hi, 
Next time please ask question in [google group](https://groups.google.com/forum/#!forum/daniels_code) use github for bugs/new features only

1) You dont get any values for Project 1 - 1 because its not present in both columns , you could search for Project 1 and since its present in both columns you will get to see several rows that match your search

2) Setting searchable to false , prevents from datatables / yadcf to filter that column (this is how datatables work)

3) Didn't get your sql question.

**Comment by vedmack** [comment]
In case of any further questions please use the google group
