### ISSUE TITLE
YADCF only TIME filter

### ISSUE THREAD

**Issue by GMEHTA1981** [vedmack/yadcf#168]
Hello Daniel,

I have come across the need to filter records by time.
For eg: filter records entered today (can be done with date filter) after 4:00 PM (no clock / time filter yet).

I don't see the filter is capable of this feature as yet.
It will be great feature.

Please can you add it to the enhancement list.

**Comment by vedmack** [comment]
Do you mean something like the [this timepicker](http://trentrichardson.com/examples/timepicker/)? and are you looking for a time only filter or date + time filter ? 

p.s It will take time due to a lack of my time :|

**Comment by GMEHTA1981** [comment]
Looking for only time filter for now !

**Comment by vedmack** [comment]
Don't see much sense in a time filter, how about a time range filter, like from time A to time B ?
any recommended time plugins ? or you were thinking about two text inputs in which user will type the time A and time B ?

**Comment by vedmack** [comment]
Since [0.8.9.beta.21](https://github.com/vedmack/yadcf/blob/240e22df6f78f4a7b9fd7a99f8c6598ab6119688/jquery.dataTables.yadcf.js) it is possible, see [showcase sample](http://yadcf-showcase.appspot.com/dom_bootstrap_time.html) (code snippet there too)
in short use `date_format: 'hh:mm'` or  `date_format: 'HH:mm'` along with `datepicker_type: 'bootstrap-datetimepicker'`
