### ISSUE TITLE
Range Number filter misses corner values.

### ISSUE THREAD

**Issue by gauravjhs** [vedmack/yadcf#209]
Range number slider misses highest value(decimal values) and always shows 1 less result once we open the filter.

**Comment by vedmack** [comment]
Provide a sample that reproduces the issue , you can use the [following jsbin](http://jsbin.com/sezuduvuyu/edit?js,output)

**Comment by gauravjhs** [comment]
Please look <a href="http://jsbin.com/yakakufori/edit?html,js">Jsbin</a>. Also resetting the number filter is not working.

**Comment by vedmack** [comment]
Its how jquery slider works, you can solve it by using the [step](http://api.jqueryui.com/slider/#option-step) property, and now you use yadcf to pass it for you by using the `filter_plugin_options: {step: 0.01}` or `filter_plugin_options: {step: 0.0001}` depend on your values in that column (grab the latest yadcf version.

**Comment by gauravjhs** [comment]
Thanks for the solution Vedmack.
One suggestion: There are lot of great select plugins out there in the market. What I have seen in your code is that you initialize the select2 plugin and if some value changes, refresh it so that new values are reflected.
If you can allow users to set these two function then any select plugin can be used.

Currently we are using http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/ plugin.

**Comment by vedmack** [comment]
yadcf supports chosen and select2 see [docs](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L180) , I did implemented the change/update inside of yadcf to ease the use of the yadcf users, *just set the `select_type` and everything will work...* you can open a new issue asking for that select plugin support or even better add it to yadcf yourself because there are already open issues and I'm lucking of a spare time recently...
