### ISSUE TITLE
With datatables Responsive plugin, column titles get 'x' appended in child row

### ISSUE THREAD

**Issue by seguemark** [vedmack/yadcf#228]
I'm using the dataTables.response.js plugin in addition to yadcf.  On responsive columns, when they are removed from the table and their content is instead placed in the child row, the title of the column changes - an 'x' is appended.  This behavior can be seen in the sample at http://yadcf-showcase.appspot.com/DOM_Ajax_Multiple_1.10.html as well.  

See for example that when the "Platform(s)" column is hidden by the responsive plugin, the title in the child row is "Platform(s)x".  It is pulling the x from the yadcf clear button's text 'x'.

**Comment by vedmack** [comment]
It was fixed in the latest datatales [responsive plugin](https://github.com/DataTables/Responsive/commit/1e262ca88a659f9cca6bed8cb6056b62edb04165) I've updated yadcf showcase (with thr latest [dataTables.responsive.js](https://raw.githubusercontent.com/DataTables/Responsive/1e262ca88a659f9cca6bed8cb6056b62edb04165/js/dataTables.responsive.js)) and it works fine now
