### ISSUE TITLE
".selector" deprecated on jQuery 1.9+

### ISSUE THREAD

**Issue by subgurim** [vedmack/yadcf#283]
Hi!

Your (excellent) plugin uses lots of ".selector", which is deprecated as of jquery 1.9+.

So the plugin doesn't work for jQuery 1.9+

Any roadmap for this issue?

Thanks!

**Comment by vedmack** [comment]
Hi,

Where did you see that *deprecation*? I couldn't find any mentioning about it, and even on jquery official site it is used with a jquery-1.10.2 version, [see here](https://api.jquery.com/class-selector/).

I think there is some other issue in your page... feel free to ask a question on [stackoverflow.co](http://stackoverflow.com/questions/tagged/yadcf)

**Comment by subgurim** [comment]
Hi!

Thanks for your quick answer and sorry if I've not explained very well the issue.

Look at https://api.jquery.com/selector/ which is deprecated.

As far as I understand, this jQuery property is used in the plugin lots of times.

Please, excuse me if I'm wrong.

**Comment by vedmack** [comment]
You are right, `.selector`  was deprecated since 1.7 but still present in the latest versions of jquery and  yadcf is also working with the latest version of jquery without any problems.
Since this issue is related to [#96 issue](https://github.com/vedmack/yadcf/issues/96) I will keep it closed and the moment I fix the [#96 issue](https://github.com/vedmack/yadcf/issues/96) there will be no use of the selector at all...

**Comment by subgurim** [comment]
Thanks!!

Only one remark, yadcf works for me if I don't use yadcf.init, except for "range-number" which uses ".selector" internally.

I'll suscribe for #96 waiting for a solution.

Thanks and great job!

**Comment by vedmack** [comment]
you should use `yadcf.init` only when you are using the capital *D* datatables constructor as to the `range-number` issue, I jsut checked with *jquery-1.12.0* and it works just fine, so you can post a questoin on [stackoverflow.com](http://stackoverflow.com/questions/tagged/yadcf) with a jsbin sample and I will see what went wrong there.
