### ISSUE TITLE
localstorage use?

### ISSUE THREAD

**Issue by Emwat** [vedmack/yadcf#318]
Not sure if DataTables or yadcf, but seeing there's an example in yadcf based on Naruto, I thought I'd try here.

I'm seeing a lot of local storage containing "naruto":"kurama" .  Not sure why as I'm loading mostly server data. 

I'm on version 0.8.9

**Comment by vedmack** [comment]
When datatables is used along with `stateSave` option, I have to store the data of the yadcf filters in datatables state saving mechanism, by saying `lot of local storage containing "naruto":"kurama"`? you mean what? because local storage is based on keys... there should be more than one `naruto` key...

**Comment by Emwat** [comment]
I have a lot of instances of datatables, so for every instance, there's Naruto.

**Comment by vedmack** [comment]
do you use stateSave in those datatables instances?

**Comment by Emwat** [comment]
Yes.

**Comment by Emwat** [comment]
I guess it's not a real issue.  I thought it was just something left over from your examples.
