### ISSUE TITLE
min version availability

### ISSUE THREAD

**Issue by louking** [vedmack/yadcf#330]
Thanks for adding yadcf to the jsdelivr cdn. This will make it much easier for me (and I assume others) to upgrade as new releases are made available.

When you have time, it would be great if you could build a minimized version and store it there as well.

Thanks again for the awesome package!

**Comment by vedmack** [comment]
Hi, since some one [requested yadcf on cdnjs](https://github.com/cdnjs/cdnjs/issues/9197) , and they uploaded all yadcf version to their cdn and they did minification to js and css (of all yadcf versions!)

so you can grab it [from cdnjs github repo](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/yadcf/0.9.0) or via [the cdnjs website](https://cdnjs.com/libraries/yadcf)
