### ISSUE TITLE
Non-inline JS

### ISSUE THREAD

**Issue by leonelwilliams** [vedmack/yadcf#373]
Currently in order to use yadcf with [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) one has to add the `unsafe-inline` policy due to the added on* attributes to the HTML (e.g. `onchange`). From what I understand adding `unsafe-inline` is suboptimal as it works around one of the nice safety features CSP provides

Would it be possible/feasable to use [`.on()`](https://api.jquery.com/on/) or similar for filtering instead of inline script?

**Comment by vedmack** [comment]
I don't think it will be possible because most of the actions that are related to yadcf must happen before the actions of datatables and in most cases it will prevent from the original dt action to happen (filter instead of sort) any way, I think that there are more fine grained solutions rather then using the `unsafe-inline`, for example *specifying the base64-encoded hash of the source code* , [see the following article](https://developer.chrome.com/extensions/contentSecurityPolicy) / do additional research. Please update this thread in case you will use some other solution.

**Comment by leonelwilliams** [comment]
Thanks for the reply! Unfortunately hashes and nonces are limited to `<script>` tags and won't work for other elements

**Comment by troysmith31** [comment]
I'm have the same issue.  Any suggestions on a work around?

**Comment by stringfellow** [comment]
Plus one - any changes possible here?

**Comment by stringfellow** [comment]
I think https://github.com/vedmack/yadcf/pull/675 fixes this issue.

**Comment by vedmack** [comment]
I have merged @stringfellow PR, let me know how it works for you
