### ISSUE TITLE
Select2, Multi-Select & externally_triggered, custom placeholder does not appear.

### ISSUE THREAD

**Issue by lenamtl** [vedmack/yadcf#380]
Hi,
My application is multilanguage so I need custom placeholder.

I'm using Select2, Multi-Select & externally_triggered 
the custom placeholder does not appear, only the one provided as default in yadcf code.

On single select with yadcf the custom placeholder is ok.

On Select2 & multi-select alone (without  yadcf) the custom placeholder is ok.

Any clue how to fix this?

I'm using Select2 4.0.3 the full version.

Thanks

**Comment by lenamtl** [comment]
Sorry I have no live link.
If you request a live link does it mean you cannot reproduce?

**Comment by vedmack** [comment]
in general my request does not indicative such a thing, but this time I did try to reproduce but it works just fine for me, so you will have to create a test page (it take 5 minutes max, you can [grab yadcf from cdn](https://cdnjs.com/libraries/yadcf) )

**Comment by lenamtl** [comment]
I just create a test to reproduce see under label the extern select2 have the default placeholder
https://jsfiddle.net/lenamtl/Lp2sdud1/
Please let me know what I am doing wrong
Thanks

**Comment by vedmack** [comment]
Oh... you were using select2 placeholder property... In that case you should use yadcf `filter_default_label` for that placeholder because under the hood I use it for the `data-placeholder` in multi select. You were right to expect that the `placeholder` will work, but since the `filter_default_label` works just fine I wont support the usage of `placeholder` for `select_type_options`. 
[See working jsfiddle](https://jsfiddle.net/Lp2sdud1/4/)

**Comment by lenamtl** [comment]
Thanks for the info
