### ISSUE TITLE
Title problem with Select2, Multi-select, empty values 

### ISSUE THREAD

**Issue by lenamtl** [vedmack/yadcf#383]
Hi,

I'm having this problem 
when using Select2, Multi-select with empty values
```
data: [' '],
    append_data_to_table_data: 'before',
    filter_match_mode: 'exact',
```

I'm looking for a way to have a title display for the empty selection
because there is no name for empty selection and this is not visible to the user that he can select empty.

Once selected here is the result if empty is selected, there is no title
`<li class="select2-selection__choice" title=""><span class="select2-selection__choice__remove" role="presentation">×</span></li>`

See the example and try to select empty in First column
http://jsfiddle.net/lenamtl/epagqe6s/7/

So it's need to be fixed at 2 places in the select dropdown
and into the selected tag.

Any solution is welcome, if there is something for this already please let me know.

Thanks

Update: I did some test with label almost ok

I have tried this 
data: [ {value:' ', label:'Others' }],
https://jsfiddle.net/lenamtl/p1t8zu9z/7/

The only problem is that the tag for Others is not created /does not appear when selected.
But it's appear into the dropdown list.

When doing the same thing on my system the label does not appear into the dropdown list but it does in tag list.... I'm confused

**Comment by vedmack** [comment]
Hi,

Since there seems to be some sort of issue with yadcf/select2 and empty string for filtering I can suggest the following solutions: 

1) Use regex ([see this jsfiddle](https://jsfiddle.net/p1t8zu9z/12/)) - 

`    data: [ {value:'^$', label:'Others' }],
    filter_match_mode: 'regex',`

2) Use Chosen plugin instead select2 ([see this jsfiddle](https://jsfiddle.net/p1t8zu9z/13/))

3) Use[ datatables HTML5 data-* attributes](https://datatables.net/examples/advanced_init/html5-data-attributes.html) ,  ([see this jsfiddle](https://jsfiddle.net/p1t8zu9z/15/))
