### ISSUE TITLE
Incompatible with sScrollX/sScrollY

### ISSUE THREAD

**Issue by spamguy** [vedmack/yadcf#43]
Hi -- first off, great tool!

This ticket is more or less a clone of #13 with some expansion. To start from the beginning, YADCF renders oddly when DataTables' sScrollX/sScrollY is enabled. Modifying the included example.html triggers it right away:

```
$(document).ready(function(){
  $('#example').dataTable({sScrollX: '100%'}).yadcf([
        {column_number : 0},
        {column_number : 1,  filter_type: "range_number_slider", filter_container_id: "external_filter_container"},
        {column_number : 2, data: ["Yes", "No"], filter_default_label: "Select Yes/No"},
        {column_number : 3, text_data_delimiter: ",", filter_type: "auto_complete"},
        {column_number : 4, column_data_type: "html", html_data_type: "text", filter_default_label: "Select tag"}]);
});
```

Also give the div 'container' an arbitrary length -- say, 500px. In the result, note how the table renders strangely all around: the table's width isn't accurate (comment out the .yadcf() to compare), column headers display separate from the filter row, the sort arrows render twice, etc.

Everything above applies to sScrollY too.

The previous ticket #13 claimed to have a workaround, but I just got an alert() error from YADCF when I tried it.

**Comment by the86freak** [comment]
actually this doesn't seem to work in the latest version anymore in your example:
http://yadcf-showcase.appspot.com/ajax_mData_source.html

Yes, there's scroll-bar and you can also swipe it left/right for about a pixel.
But even though you can see, that the header is not scrolled.

What would you suggest to fix that? Do you see a workaround? I'm happy to help out there.

**Comment by vedmack** [comment]
As to the scrollY , it works in the showcase, as to the scrollX, I havent used it in that page, and I don't really know why that horizontal scroll appears there, but it will appear even without using the yadcf (so its not related to yadcf), my fix was to place the filters in the right table headers, I don't really know that horizontal bar appears, but I guess you can get the answer on datatables forum , sorry.

Anyway, if you want to know if something happens because of yadcf or not , just comment out yadcf init code and see how datatables behaves.

**Comment by vedmack** [comment]
@the86freak it works just fine with the [0.8.8](http://jsfiddle.net/3h7k25fh/81/) / [0.8.9](http://jsfiddle.net/3h7k25fh/82/) and looks the same as your jsfiddle.

**Comment by the86freak** [comment]
@vedmack first: thanks for having a look into that.

you'r right, if you leave the css with v 0.8.8

if you also change that to [0.8.8](http://jsfiddle.net/The86Freak/3h7k25fh/89/) the header is not scrolling anymore.

Further investigation showed, that if I remove:

126	.dataTables_scrollHead {			
127	        overflow: visible !important;			
128	}

from ../vedmack/yadcf/0.8.8/jquery.dataTables.yadcf.css
the header also scrolls again.
Is that a side-effect with another css or do you think you can remove that?

**Comment by vedmack** [comment]
@the86freak , will get back to you in a day or two

**Comment by vedmack** [comment]
@the86freak, Can you provide me an example of improper behaviour of yadcf css with a scrollX or scrollY ? because I can't understand your issue.

**Comment by the86freak** [comment]
@vedmack sure, no problem. I'll sum up:
The problem is, that when the table is bigger as the parent container (viewport), the overlapping part of the table (and its headers) are 'disapearing' - of course.
So when you define the width with scrollX, I excpect that I can scroll the table(content) horizontal and then also the header schould scroll according with the table-body. 

This works with css-version 0.8.7: http://jsfiddle.net/The86Freak/q6bmyju9/

since css-version 0.8.8 it doesn't work anymore: http://jsfiddle.net/The86Freak/q6bmyju9/2/

**Comment by vedmack** [comment]
@the86freak ,'overflow: visible !important; '  will be removed in next beta
