### ISSUE TITLE
Space wrapped items in a select2 select or multi_select

### ISSUE THREAD

**Issue by JeroenvO** [vedmack/yadcf#454]
![afbeelding](https://user-images.githubusercontent.com/5551571/38176228-95e438ba-35eb-11e8-9a40-f3cfe7d77e73.png)
See:
https://jsfiddle.net/jeroenvo/bzc853hc/28/
when an item in an HTML field is wrapped in spaces, the value is visible in the dropdown but not in visible in the input box when the item is selected.
Happens with select2 with normal select and also with multi_select.

Maybe strip spaces at both ends of the cell data would be a nice fix.

**Comment by vedmack** [comment]
from  what I have seen the generated select element in valid with options that are matching the original values in the table column, it might be a bug in the select2 plugin, not sure... I suggest you to trim the original value in the table column, if you will provide a test page showing that the select2 plugin does work differently (without yadcf) I will try to see again where the value is getting messed

**Comment by JeroenvO** [comment]
I've added a simple select2 dropdown to the fiddle, see https://jsfiddle.net/jeroenvo/bzc853hc/41/
It seems to work when the select2 options are provided directly.

**Comment by vedmack** [comment]
Hi
It doesn't work because of select2 got some issues with the spaces, without select2 it does work, there is a way to fix it - by trimming the parsed text, by placing `col_inner_data = $.trim(col_inner_data);` inside `parseTableColumn` right after `if (col_inner_data || col_inner_data_helper) { if (!col_inner_data_helper) {` but I prefer not to place it there because that might have side effects.
As to the `sample-select` init (pure select2) with spaces that you did, the spaces in the the options are being trimmed by select2 and thats why it works as expected (while the spaces that parsed by yadcf from html span tag are preserved and passed to to select2 (which in turn does not work properly)

**Comment by JeroenvO** [comment]
Ok, thanks for the explanation!
